const engagements = [
    {
        id: "tech-summit-2024",
        title: "Global Tech Leadership Summit 2024",
        event: "Tech Leadership Summit",
        location: "Singapore",
        date: "2024-03-15",
        endDate: "2024-03-16",
        type: "keynote",
        topic: "ai-leadership",
        topicTitle: "Building AI-Ready Organizations",
        audience: "500+ CTOs and Engineering Leaders",
        organizer: "Tech Leaders Asia",
        website: "https://techsummit.asia",
        status: "confirmed",
        featured: true,
        description: "Opening keynote on preparing technical organizations for AI transformation",
        image: "/images/events/tech-summit-2024.jpg",
    },
    {
        id: "startup-scale-workshop",
        title: "Scaling Engineering Teams Workshop",
        event: "Scale-Up Academy",
        location: "London, UK",
        date: "2024-04-22",
        type: "workshop",
        topic: "scaling-innovation",
        topicTitle: "Scaling Innovation Through Hypergrowth",
        audience: "50 Scale-up CTOs and Engineering Leaders",
        organizer: "European Scale-Up Network",
        status: "confirmed",
        featured: true,
        description: "Interactive workshop on maintaining innovation culture during rapid growth",
    },
    {
        id: "ai-ethics-panel",
        title: "AI Ethics in Technical Leadership",
        event: "Future of Work Conference",
        location: "San Francisco, CA",
        date: "2024-05-08",
        type: "panel",
        topic: "ai-leadership",
        audience: "300+ Technology Leaders",
        organizer: "Future Work Institute",
        status: "confirmed",
        featured: false,
        description: "Panel discussion on ethical AI implementation in enterprise environments",
    },
    {
        id: "devops-world-2023",
        title: "DevOps World 2023",
        event: "DevOps World",
        location: "New York, NY",
        date: "2023-09-27",
        type: "keynote",
        topic: "cross-cultural-teams",
        topicTitle: "Leading Global Technical Teams",
        audience: "2000+ DevOps Professionals",
        organizer: "CloudBees",
        status: "completed",
        featured: true,
        description: "Keynote on building high-performing distributed technical teams",
        recording: "https://youtube.com/watch?v=example",
        slides: "/downloads/devops-world-2023-slides.pdf",
        feedback: {
            rating: 4.8,
            responses: 156,
            highlights: [
                "Practical insights on remote team management",
                "Excellent real-world examples",
                "Clear actionable frameworks",
            ],
        },
    },
    {
        id: "venture-summit-2023",
        title: "Technical Due Diligence Masterclass",
        event: "Venture Capital Summit",
        location: "Palo Alto, CA",
        date: "2023-11-14",
        type: "masterclass",
        topic: "technical-due-diligence",
        audience: "25 VCs and Investment Partners",
        organizer: "Silicon Valley Venture Association",
        status: "completed",
        featured: true,
        description: "Full-day masterclass on evaluating technical organizations for investment",
        feedback: {
            rating: 4.9,
            responses: 23,
            highlights: [
                "Comprehensive framework for technical assessment",
                "Valuable case study analysis",
                "Immediately applicable methodologies",
            ],
        },
    },
    {
        id: "women-tech-leadership",
        title: "Inclusive Technical Leadership",
        event: "Women in Tech Leadership Conference",
        location: "Toronto, Canada",
        date: "2023-10-12",
        type: "workshop",
        topic: "cross-cultural-teams",
        audience: "80 Women Technology Leaders",
        organizer: "Women in Tech Canada",
        status: "completed",
        featured: false,
        description: "Workshop on building inclusive and diverse technical teams",
    },
]

module.exports = function () {
    return {
        upcoming: engagements.slice(0, 3),
        past: engagements.slice(3),
        stats: {
            totalEngagements: engagements.length,
            countriesSpoken: 12,
            averageRating: 4.7,
        }
    }
}
